### ISSUE TITLE
How to get differential loops after using pareidolia?

### ISSUE THREAD

**Issue by YiweiNiu** [cmdoret/pareidolia#10]
Hi,

Thanks for developing this tool.

I tried pareidolia on given regions (through `--bed2d-file`) to detect changes in loops between two conditions.

Then I got a table like this.

```
chrom1	start1	end1	chrom2	start2	end2	bin1	bin2	diff_score	cnr
chr1	63670000	63680000	chr1	64440000	64450000	6367.0	6444.0	0.0	0.14466463119020248
chr1	63640000	63650000	chr1	64450000	64460000	6364.0	6445.0	1e-08	10.0
chr1	63760000	63770000	chr1	64450000	64460000	6376.0	6445.0	1e-08	10.0
chr1	63660000	63670000	chr1	64490000	64500000	6366.0	6449.0	1e-08	10.0
chr1	63700000	63710000	chr1	64430000	64440000	6370.0	6443.0	1e-08	10.0
chr1	63720000	63730000	chr1	64490000	64500000	6372.0	6449.0	1e-08	10.0
chr1	63750000	63760000	chr1	64480000	64490000	6375.0	6448.0	1e-08	10.0
chr1	63730000	63740000	chr1	64440000	64450000	6373.0	6444.0	1e-08	10.0
chr1	63690000	63700000	chr1	64470000	64480000	6369.0	6447.0	1e-08	10.0
```

I wonder how to get differential loops from this file. What threshold do you recommend filtering?

I found [a similar issue](https://github.com/koszullab/pareidolia/issues/6) about this, but that thread did not give a specific threshold to get differential loops.

Bests,
Yiwei

**Comment by cmdoret** [comment]
Hi @YiweiNiu,

There is currently no p-values or automatic / statistical way to select optimal thresholds.
The thresholds are set to "sane" defaults, but may need to be manually adjusted, and this likely requires inspection of the data.

You could then rank, or filter the patterns on `diff_score` and `cnr` depending on your application. But pareidolia can currently not give you a list of coordinates with significantly different intensities with e.g. alpha 0.05.

**Comment by YiweiNiu** [comment]
Thanks for your help. I would try this.
