### ISSUE TITLE
Control the min distance of pareidolia like chromosight

### ISSUE THREAD

**Issue by Linhua-Sun** [cmdoret/pareidolia#8]
Hi:
    I am testing pareidolia to identify DE loops between Treat and Ctrl conditions. I found that chromosight can detect and quantify loops with min and max distance options. While, **pareidolia only have max distance option. Is it possible to have min distance option for pareidolia**. The default min distance option for pareidolia is 20 kb (I want to set it smaller). I also appended the normal output for pareidolia.
    I am also wondering whether you will publish a paper for pareidolia? I will use pareidolia for one or two papers in the in the near future. Thanks for you wonderful work which helps a lot.

```
Loading default parameter for kernel 'loops'...
pearson_thresh: 0.0
min_dist: 20000
max_dist: 100000
Changes will be computed relative to condition: Light
      chrom1    start1      end1  ...      bin2    diff_score        cnr
0          1      3000      4000  ...      50.0 -6.793506e-02   0.314328
1          1      5000      6000  ...      25.0  4.322519e-02   0.237540
2          1      8000      9000  ...      45.0  2.190087e-02   1.388390
3          1     11000     12000  ...      72.0 -8.693999e-02   0.428035
4          1     12000     13000  ...      32.0 -2.915378e-02   0.14159

[40487 rows x 10 columns]

```

Thanks!
Linhua Sun

**Comment by cmdoret** [comment]
Hi @Linhua-Sun 

Indeed, thanks for your feedback ! I just added that feature a while back in the python API, but somehow forgot to expose it in the command line.
I added the  `--min-dist` option in the master branch. It passes the tests, but would you mind trying it out and see if it works as you would expect ? If so I'll make it into a new release.

I do not have any plan to publish the software (don't really have the time right now). For now the only option is to cite the Zenodo record for the appropriate version, see bottom of README. It is also described in more details in my thesis (pp. 69-72, [PDF available here](https://github.com/cmdoret/phd/releases/tag/20211122-01)), but it will still take some time before the thesis is uploaded on an official repository and gets a digital identifier (the administrative process is pretty slow).

Cheers,
Cyril

**Comment by Linhua-Sun** [comment]
Hi @cmdoret 
I have tested the new pareidolia with `--min-dist` option. It woks. Thanks a lot.
Best wishes!
Linhua

**Comment by cmdoret** [comment]
Thanks, I'll make it into a release!
